### ISSUE TITLE
[Enhancement] Publish Xappium to nuget.org

### ISSUE THREAD

**Issue by ThinhTranA** [Xappium/xappium.uitest#20]
## Summary
I understand there might be some work in progress,
But is it possible to publish Xappium to nuget.org ? 

## Use case
Currently, to run UI test with Xappium, I have to download the whole project and add preference locally. A nuget package (preview) would make it much simpler to use Xappium.

**Comment by dansiegel** [comment]
We've discussed this issue in the past. The reason we haven't published it yet is that while the cli tool works locally it fails in CI. If it's something you'd like to help us with, we certainly welcome the help, and it would speed up getting a package published.

**Comment by ThinhTranA** [comment]
I certainly like to help, but I'm not sure if I have the skill and knowledge for this issue.

Currently, I'm using `Xamarin.UITest` project only with Specflow, without the CLI tool and other projects.
Running test with `dotnet test` and have it working running in Github Action. Though I'm not too sure if this is the optimal way of using it.

**Comment by ThinhTranA** [comment]
Awesome,  thank you 😊.
